/**
 * T12.11 (platform seam) — `create-site.mjs --json` programmatic mode.
 *
 * CMS-Agent's one-call site-duplication driver (`site.duplicate`) invokes this
 * CLI as a subprocess and parses stdout. This test pins the machine contract:
 *
 *   1. `--json` emits EXACTLY ONE line of parseable JSON on stdout — no prose
 *      mixed in — on both the `--dry-run` path and the idempotent
 *      noop-existing path (an already-scaffolded tenant, which touches neither
 *      disk nor network).
 *   2. The document is create_site_result.v1: slug/dir/ids/plannedFiles, the
 *      flattened env checklist (env var NAMES + classes only), the blob-store
 *      list, and the §admin human-gate steps.
 *   3. No secret VALUES can appear: generatable rows are reported as
 *      `autoGenerated: true` booleans, never as minted values.
 *
 * Plain, uncompiled node:test run directly against the real repo (the
 * genesis-manifest.test.mjs pattern), picked up by `npm test`'s
 * `node --test tests/scripts/*.test.mjs` leg.
 */
import assert from 'node:assert/strict';
import test from 'node:test';

import { ENV_CHECKLIST, buildPlan, main } from '../../packages/core/cli/create-site.mjs';

const captureStdout = async (run) => {
  const lines = [];
  const original = console.log;
  console.log = (line) => lines.push(String(line));
  try {
    await run();
  } finally {
    console.log = original;
  }
  return lines;
};

const withoutEnvToken = async (run) => {
  const saved = process.env.NETLIFY_API_TOKEN;
  delete process.env.NETLIFY_API_TOKEN;
  try {
    return await run();
  } finally {
    if (saved !== undefined) process.env.NETLIFY_API_TOKEN = saved;
  }
};

const flatRowCount = ENV_CHECKLIST.reduce((sum, group) => sum + group.rows.length, 0);

test('--dry-run --json emits exactly one parseable create_site_result.v1 line, no prose', async () => {
  const lines = await withoutEnvToken(() => captureStdout(() => main(['--name', 'acme', '--dry-run', '--json'])));
  assert.equal(lines.length, 1, 'stdout must be exactly one line for a machine caller');
  const result = JSON.parse(lines[0]);
  assert.equal(result.contract, 'create_site_result.v1');
  assert.equal(result.ok, true);
  assert.equal(result.mode, 'dry-run');
  assert.equal(result.slug, 'acme');
  assert.equal(result.dir, 'sites/acme');
  assert.equal(result.ids.siteId, 'site_acme');
  assert.equal(result.plannedFiles, buildPlan({ name: 'acme' }).files.length);
  assert.equal(result.scaffolded, false);
  assert.equal(result.netlify, null);
  assert.equal(result.netlifyPlanned, false);
  // Env checklist: every row, names + classes only, with the auto-generatable rows flagged.
  assert.equal(result.envChecklist.length, flatRowCount);
  const adminEmails = result.envChecklist.find((row) => row.name === 'ADMIN_EMAILS');
  assert.equal(adminEmails.cls, 'per-site');
  assert.equal(adminEmails.autoGenerated, false);
  const publishSecret = result.envChecklist.find((row) => row.name === 'PUBLISH_SECRET');
  assert.equal(publishSecret.autoGenerated, true);
  // No secret values by construction: rows carry exactly the metadata keys, never a value.
  for (const row of result.envChecklist) {
    assert.deepEqual(Object.keys(row).sort(), ['autoGenerated', 'cls', 'group', 'inheritFromPdfTool', 'name', 'note']);
  }
  assert.deepEqual(result.adminBootstrapHumanGate, ['enable_netlify_identity', 'set_admin_emails', 'invite_first_owner']);
  assert.ok(result.coreBlobStores.includes('site-objects'));
});

test('--json on an already-scaffolded tenant reports noop-existing and touches nothing', async () => {
  // sites/platform exists in this repo; the no-provision-only path returns before disk or network.
  const lines = await withoutEnvToken(() => captureStdout(() => main(['--name', 'platform', '--json'])));
  assert.equal(lines.length, 1);
  const result = JSON.parse(lines[0]);
  assert.equal(result.contract, 'create_site_result.v1');
  assert.equal(result.mode, 'noop-existing');
  assert.equal(result.scaffolded, false);
  assert.equal(result.alreadyScaffolded, true);
  assert.equal(result.netlify, null);
});
