/**
 * T12.11 (platform seam) — `create-site.mjs --json` programmatic mode.
 *
 * CMS-Agent's one-call site-duplication driver (`site.duplicate`) invokes this
 * CLI as a subprocess and parses stdout. This test pins the machine contract:
 *
 *   1. `--json` emits EXACTLY ONE line of parseable JSON on stdout — no prose
 *      mixed in — on both the `--dry-run` path and the idempotent
 *      noop-existing path (an already-scaffolded tenant, which touches neither
 *      disk nor network).
 *   2. The document is create_site_result.v1: slug/dir/ids/plannedFiles, the
 *      flattened env checklist (env var NAMES + classes only), the blob-store
 *      list, and the §admin human-gate steps.
 *   3. No secret VALUES can appear: generatable rows are reported as
 *      `autoGenerated: true` booleans, never as minted values.
 *
 * W3 (Wolf, 2026-09-09) extends the same file with the GENESIS POLICY's teeth,
 * because they live on this exact seam: a mint that omits a required baseline
 * is refused at `buildPlan`, so it is refused on the `--dry-run` path, on the
 * `--json` path, and on the real scaffold identically — before any file is
 * written and long before a Netlify site exists. The machine-readable half of
 * that refusal is part of this file's contract, not a separate one.
 *
 * Plain, uncompiled node:test run directly against the real repo (the
 * genesis-manifest.test.mjs pattern), picked up by `npm test`'s
 * `node --test tests/scripts/*.test.mjs` leg.
 */
import assert from 'node:assert/strict';
import test from 'node:test';

import { ENV_CHECKLIST, buildPlan, genesisRefusalResult, main } from '../../packages/core/cli/create-site.mjs';
import {
  FLEET_GENESIS_POLICY,
  clearGenesisPolicyProviderForTests,
  setGenesisPolicyProvider,
} from '../../packages/core/cli/genesis-manifest.mjs';

const captureStdout = async (run) => {
  const lines = [];
  const original = console.log;
  console.log = (line) => lines.push(String(line));
  try {
    await run();
  } finally {
    console.log = original;
  }
  return lines;
};

const withoutEnvToken = async (run) => {
  const saved = process.env.NETLIFY_API_TOKEN;
  delete process.env.NETLIFY_API_TOKEN;
  try {
    return await run();
  } finally {
    if (saved !== undefined) process.env.NETLIFY_API_TOKEN = saved;
  }
};

const flatRowCount = ENV_CHECKLIST.reduce((sum, group) => sum + group.rows.length, 0);

test('--dry-run --json emits exactly one parseable create_site_result.v1 line, no prose', async () => {
  const lines = await withoutEnvToken(() => captureStdout(() => main(['--name', 'acme', '--dry-run', '--json'])));
  assert.equal(lines.length, 1, 'stdout must be exactly one line for a machine caller');
  const result = JSON.parse(lines[0]);
  assert.equal(result.contract, 'create_site_result.v1');
  assert.equal(result.ok, true);
  assert.equal(result.mode, 'dry-run');
  assert.equal(result.slug, 'acme');
  assert.equal(result.dir, 'sites/acme');
  assert.equal(result.ids.siteId, 'site_acme');
  assert.equal(result.plannedFiles, buildPlan({ name: 'acme' }).files.length);
  assert.equal(result.scaffolded, false);
  assert.equal(result.netlify, null);
  assert.equal(result.netlifyPlanned, false);
  // Env checklist: every row, names + classes only, with the auto-generatable rows flagged.
  assert.equal(result.envChecklist.length, flatRowCount);
  const adminEmails = result.envChecklist.find((row) => row.name === 'ADMIN_EMAILS');
  assert.equal(adminEmails.cls, 'per-site');
  assert.equal(adminEmails.autoGenerated, false);
  const publishSecret = result.envChecklist.find((row) => row.name === 'PUBLISH_SECRET');
  assert.equal(publishSecret.autoGenerated, true);
  const cmsAgentToken = result.envChecklist.find((row) => row.name === 'CMS_AGENT_MCP_TOKEN');
  assert.equal(cmsAgentToken.autoGenerated, false);
  assert.equal(cmsAgentToken.provisionedByGenesis, true);
  // R8.1: TRACKING_SINK_URL/TOKEN are flagged team-inherited (never copied from
  // the operator env into a site); PDF_TOOL_BASE_URL stays inheritFromPdfTool
  // only — the two team-vs-service inheritance mechanisms are distinct.
  const trackingSinkUrl = result.envChecklist.find((row) => row.name === 'TRACKING_SINK_URL');
  assert.equal(trackingSinkUrl.teamInherited, true);
  assert.equal(trackingSinkUrl.inheritFromPdfTool, false);
  const trackingSinkToken = result.envChecklist.find((row) => row.name === 'TRACKING_SINK_TOKEN');
  assert.equal(trackingSinkToken.teamInherited, true);
  const pdfToolBaseUrl = result.envChecklist.find((row) => row.name === 'PDF_TOOL_BASE_URL');
  assert.equal(pdfToolBaseUrl.inheritFromPdfTool, true);
  assert.equal(pdfToolBaseUrl.teamInherited, false);
  // No secret values by construction: rows carry exactly the metadata keys, never a value.
  for (const row of result.envChecklist) {
    assert.deepEqual(Object.keys(row).sort(), ['autoGenerated', 'cls', 'group', 'inheritFromPdfTool', 'name', 'note', 'provisionedByGenesis', 'teamInherited']);
  }
  assert.deepEqual(result.adminBootstrapHumanGate, ['enable_netlify_identity', 'set_admin_emails', 'invite_first_owner']);
  assert.ok(result.coreBlobStores.includes('site-objects'));
});

// ─── W3: the genesis policy's teeth at the mint ────────────────────────────
//
// The shipped policy requires NOTHING, so every assertion above ran under it
// already — that is the first test below, stated explicitly rather than left
// implicit, because "W3 changed no existing mint's outcome" is the claim that
// most needs evidence.

const withPolicy = (requiredArtifacts, run) => {
  setGenesisPolicyProvider(() => ({ requiredArtifacts }));
  try {
    return run();
  } finally {
    clearGenesisPolicyProviderForTests();
  }
};

const strategySeedOf = (plan) =>
  plan.files.find((file) => file.path.endsWith('/seeds/strategy-seed-data.mjs')).content;

test('the shipped policy is empty: a mint with no baselines supplied passes and seeds genesis_default exactly as before', () => {
  clearGenesisPolicyProviderForTests();
  assert.deepEqual(FLEET_GENESIS_POLICY.requiredArtifacts, [], 'the fleet default requires nothing — Wolf flips it');
  const plan = buildPlan({ name: 'acme' });
  assert.ok(plan.files.length > 0);
  assert.match(
    strategySeedOf(plan),
    /"set_by": "genesis_default"/,
    'an unsupplied baseline is still seeded carrying the unset marker, not omitted'
  );
});

test("requiring editorial_strategy refuses a mint that omits it — 422 genesis_artifact_required, missing: ['editorialStrategy'], both ways out named", () => {
  withPolicy(['editorial_strategy'], () => {
    let thrown;
    try {
      buildPlan({ name: 'acme' });
    } catch (error) {
      thrown = error;
    }
    assert.ok(thrown, 'the mint must be refused, not scaffolded');
    assert.equal(thrown.code, 'genesis_artifact_required');
    assert.equal(thrown.status, 422);
    // INPUT FIELD names, never object types — what the caller would have to type.
    assert.deepEqual(thrown.missing, ['editorialStrategy']);
    assert.equal(thrown.waysOut.length, 2);
    assert.match(thrown.waysOut[0], /^supply now:/);
    assert.match(thrown.waysOut[1], /^lower the policy:/);
    assert.match(thrown.message, /SUPPLY NOW/);
    assert.match(thrown.message, /LOWER THE POLICY/);
    assert.match(thrown.message, /--editorial-strategy/);
    assert.match(thrown.message, /No files were written/);
  });
});

test('supplying the required baseline passes, and the seeded object carries provenance.set_by "agent"', () => {
  withPolicy(['editorial_strategy'], () => {
    const plan = buildPlan({ name: 'acme', editorialStrategy: { goal: 'Sell the workshop.' } });
    const seed = strategySeedOf(plan);
    assert.match(seed, /"set_by": "agent"/, 'a supplied baseline is authored, not a genesis default');
    assert.match(seed, /Sell the workshop\./);
    assert.doesNotMatch(seed, /"set_by": "genesis_default"/);
  });
});

test('every artifact the policy can require is actually supplyable — a refusal with no way out is not a refusal', () => {
  // The closed enum exists so a policy cannot demand something no flag
  // provides. This proves the other half: each one, supplied, mints cleanly.
  const supplied = {
    editorial_strategy: { editorialStrategy: { goal: 'g' } },
    editorial_voice: { editorialVoice: { name: 'v' } },
    visual_standard: { visualStandard: { palette: {} } },
    logo: { logo: { text: 'ACME' } },
    tracking_config: { trackingConfig: { consent: { posture: 'us-first' } } },
  };
  for (const [artifact, opts] of Object.entries(supplied)) {
    withPolicy([artifact], () => {
      assert.ok(buildPlan({ name: 'acme', ...opts }).files.length > 0, `${artifact} must be supplyable at mint`);
    });
  }
});

test('a malformed policy throws loudly rather than resolving to the permissive default', () => {
  // The creation-policy precedent. The permissive default is `[]`, so a silent
  // fallback would turn "Wolf required a strategy" into "nothing is required"
  // with no output at all — the one failure mode worth taking the mint down.
  for (const bad of [
    { requiredArtifacts: 'editorial_strategy' },
    { requiredArtifacts: ['editorial_stratgy'] },
    { requiredArtifacts: ['logo', 'logo'] },
    { requiredArtifacts: [], surprise: true },
    {},
    null,
  ]) {
    setGenesisPolicyProvider(() => bad);
    try {
      assert.throws(
        () => buildPlan({ name: 'acme' }),
        /Invalid genesis-policy config/,
        `${JSON.stringify(bad)} must throw, never resolve to []`
      );
    } finally {
      clearGenesisPolicyProviderForTests();
    }
  }
});

test('--json surfaces the refusal as a machine-readable document, not an unparseable stderr blob', async () => {
  // CMS-Agent's site.duplicate parses this stdout. A policy refusal it cannot
  // parse becomes "scaffold failed", which is exactly what a catalogued,
  // actionable refusal exists not to become.
  await withPolicy(['editorial_strategy', 'logo'], async () => {
    let thrown;
    const lines = await withoutEnvToken(() =>
      captureStdout(async () => {
        try {
          await main(['--name', 'acme', '--dry-run', '--json']);
        } catch (error) {
          thrown = error;
        }
      })
    );
    // main() itself throws; the CLI entry point is what prints the document,
    // so assert on the error the driver's subprocess wrapper would see and on
    // the payload it carries.
    assert.equal(lines.length, 0, 'no partial create_site_result.v1 is emitted for a refused mint');
    assert.equal(thrown.code, 'genesis_artifact_required');
    assert.deepEqual(thrown.missing, ['editorialStrategy', 'logo']);
    assert.equal(thrown.status, 422);

    // What the CLI entry point prints for that error: the SAME contract a
    // successful run emits, so a driver parses one shape either way.
    const document = genesisRefusalResult(thrown);
    assert.equal(document.contract, 'create_site_result.v1');
    assert.equal(document.ok, false);
    assert.equal(document.status, 422);
    assert.equal(document.error_code, 'genesis_artifact_required');
    assert.deepEqual(document.missing, ['editorialStrategy', 'logo']);
    assert.equal(document.ways_out.length, 2);
    assert.equal(document.scaffolded, false);
    assert.equal(document.netlify, null);
    assert.match(document.error, /SUPPLY NOW/);
    assert.match(document.error, /LOWER THE POLICY/);
    // JSON.stringify must not throw on it and must round-trip.
    assert.deepEqual(JSON.parse(JSON.stringify(document)), document);
  });
});

test('--json on an already-scaffolded tenant reports noop-existing and touches nothing', async () => {
  // sites/platform exists in this repo; the no-provision-only path returns before disk or network.
  const lines = await withoutEnvToken(() => captureStdout(() => main(['--name', 'platform', '--json'])));
  assert.equal(lines.length, 1);
  const result = JSON.parse(lines[0]);
  assert.equal(result.contract, 'create_site_result.v1');
  assert.equal(result.mode, 'noop-existing');
  assert.equal(result.scaffolded, false);
  assert.equal(result.alreadyScaffolded, true);
  assert.equal(result.netlify, null);
});
